stages:
  download_data:
    cmd: python .\scripts\data_prep.py
    deps:
    - .\scripts\data_prep.py
    outs:
    - .\data\X_test.csv
    - .\data\X_train.csv
    - .\data\y_test.csv
    - .\data\y_train.csv
  train_model:
    cmd: python .\scripts\train_model.py
    deps:
    - .\data\X_test.csv
    - .\data\X_train.csv
    - .\scripts\train_model.py
    outs:
    - .\models\train_model\model.joblib
